ALTER TYPE "SecurityEventType" ADD VALUE 'TWO_FACTOR_ENABLED';
ALTER TYPE "SecurityEventType" ADD VALUE 'TWO_FACTOR_VERIFIED';
ALTER TYPE "SecurityEventType" ADD VALUE 'TWO_FACTOR_RECOVERY_CODE_USED';
ALTER TYPE "SecurityEventType" ADD VALUE 'TWO_FACTOR_FAILED';
ALTER TYPE "SecurityEventType" ADD VALUE 'TWO_FACTOR_RESET_BY_OWNER';
